type Props = {
    id: number
    image: string
    category: string
    title: string
    author: string
    date: string
    description: string
}
let lastPostId = 0
export function getNextPostId() {
    return ++lastPostId
}
export const defaultDescription =
    'A breathless session saw a quite staggering 23 cars blanketed by just eight tenths of a second with positions changing at almost every moment. Such was the competitiveness that the ballast-laden VW of Jason Plato could only manage 22nd on the grid, although the double champion has cited an as yet unknown problem with...'

const ArrayOfAllPostsHomePage: Props[] = [
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-01.jpg',
        category: 'deals',
        title: 'Junkyard All-You-Can-Carry Sale Next Monday',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-02.jpg',
        category: 'tuning',
        title: 'Justin Bieber’s Ferrari 458 Italia Transformation',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-03.jpg',
        category: 'tuning',
        title: 'Limited Production Confirmed for McLaren 675LT',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-04.jpg',
        category: 'tuning',
        title: 'There’s Nothing Funny About Toyota’s Fuel Leaks',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-05.jpg',
        category: 'tuning',
        title: 'Hackers Seize Control of a Tesla Model S',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-06.jpg',
        category: 'tuning',
        title: 'Modify Your New Mercedes-Benz C-Class',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-07.jpg',
        category: 'tuning',
        title: 'Volvo 142 Drift Car Project Hits Swedish Street',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-08.jpg',
        category: 'life',
        title: 'Fiat Forced to Buy Back 500K Vehicles',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-09.jpg',
        category: 'life',
        title: 'BMW Overhauls Wheelchair for Paralympics',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-10.jpg',
        category: 'life',
        title: 'Mad Max Fury Road Re-Created With Go-Karts',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-11.jpg',
        category: 'life',
        title: 'Cars in Miniature Swarm Greater Boston Area',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-12.jpg',
        category: 'life',
        title: 'Get Ready for New Diesel Cadillacs',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-13.jpg',
        category: 'life',
        title: 'All But 2 Buick Models Built Overseas',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-14.jpg',
        category: 'tests',
        title: 'Volkswagen Beetle R-Line is a Little Beast',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-15.jpg',
        category: 'tests',
        title: 'Land Rover Range Rover Sport’s New Diesel V6',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-16.jpg',
        category: 'tests',
        title: 'The New Jaguar Crossover “F-Pace”',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-17.jpg',
        category: 'tests',
        title: 'Ferrari Testing Right Hand Drive California',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-18.jpg',
        category: 'tests',
        title: '2017 Ford Raptor Dominates Off-Road Trailchips',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-19.jpg',
        category: 'reviews',
        title: '2016 Chevrolet Malibu: No Yawning!',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-20.jpg',
        category: 'reviews',
        title: 'Having Fun on Country Roads with Audi R8',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-21.jpg',
        category: 'reviews',
        title: '2015 Chevrolet Camaro ZL1 Coupe',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-22.jpg',
        category: 'reviews',
        title: 'Mercedes AMG C63 S Sedan',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-23.jpg',
        category: 'reviews',
        title: 'Chevy Silverado Midnight Edition',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-24.jpg',
        category: 'reviews',
        title: 'Volkswagen Golf SportWagen TDI',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-25.jpg',
        category: 'motorSports',
        title: 'Scenes From the 2015 Pebble Beach Tour',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-26.jpg',
        category: 'motorSports',
        title: '’70s F1 cars will star at Goodwood',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-27.jpg',
        category: 'motorSports',
        title: 'Could Your Child Win a Season’s Racing?',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-28.jpg',
        category: 'motorSports',
        title: 'Octane’s Goodwood Festival of Speed',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-29.jpg',
        category: 'motorSports',
        title: 'All the Best Bits of Goodwood Motorsport',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-30.jpg',
        category: 'motorSports',
        title: 'LaFerrari, McLaren P1, and Porsche 918 On-Track',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-31.jpg',
        category: 'auto shows',
        title: 'Mercedes-Benz Plans GLE Hybrid to Debut in New York',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-32.jpg',
        category: 'auto shows',
        title: 'Two New Scion Models Confirmed for the New York Auto Show',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-33.jpg',
        category: 'oldies',
        title: 'Monterey Auctions See $393 M in Sales',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
    {
        id: getNextPostId(),
        image: '/images/Products/All-Posts/all-posts-34.jpg',
        category: 'oldies',
        title: 'What Next for the Barn Finds?',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
    },
]

export default ArrayOfAllPostsHomePage
