export type PropsPosts = {
    id: number
    title: string
    category: string
    author: string
    date: string
    description: string
    image: string
}
const defaultDescription =
    'A breathless session saw a quite staggering 23 cars blanketed by just eight tenths of a second with positions changing at almost every moment....'
export const postsArray: PropsPosts[] = [
    {
        id: 1,
        title: 'Could Your Child Win a Season’s Racing?',
        category: 'Motorsports',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-01.jpg',
    },
    {
        id: 2,
        title: 'Octane’s Goodwood Festival of Speed',
        category: 'Motorsports',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-02.jpg',
    },
    {
        id: 3,
        title: 'All the Best Bits of Goodwood Motorsport',
        category: 'Motorsports',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-03.jpg',
    },
    {
        id: 4,
        title: 'LaFerrari, McLaren P1, and Porsche 918 On-Track',
        category: 'Motorsports',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-04.jpg',
    },
    {
        id: 5,
        title: 'Mercedes-Benz Plans GLE Hybrid to Debut in New York',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-05.jpg',
    },
    {
        id: 6,
        title: 'Two New Scion Models Confirmed for the New York Auto Show',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-06.jpg',
    },
    {
        id: 7,
        title: 'Aston Martin DBX Concept: Gorgeous AWD Electric Sports Car',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-07.jpg',
    },
    {
        id: 8,
        title: 'Acura to Bring Updated RDX to 2015 Chicago Auto Show',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-08.jpg',
    },
    {
        id: 9,
        title: 'Our Picks for the Very Best from the 2015 Geneva Auto Show',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-09.jpg',
    },
    {
        id: 10,
        title: '2016 Audi Q7 Debuts with Next-Gen Styling at Detroit',
        category: 'Auto Shows',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-10.jpg',
    },
    {
        id: 11,
        title: 'Monterey Auctions See $393 M in Sales',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-11.jpg',
    },
    {
        id: 12,
        title: 'What Next for the Barn Finds?',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-12.jpg',
    },
    {
        id: 13,
        title: 'Little Knobbly Lives Again',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-13.jpg',
    },
    {
        id: 14,
        title: 'TVR stages a More Credible Comeback',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-14.jpg',
    },
    {
        id: 15,
        title: 'Holyrood Concours of Elegance',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-15.jpg',
    },
    {
        id: 16,
        title: 'That Time Bugatti Almost Built a Sedan',
        category: 'Oldies',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-16.jpg',
    },
    {
        id: 17,
        title: '400-hp BMW Diesel Just Around the Corner',
        category: 'Hi-Tech',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-17.jpg',
    },
    {
        id: 18,
        title: 'Land Rover Recreates 1948 Production Line',
        category: 'Hi-Tech',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-18.jpg',
    },
    {
        id: 19,
        title: 'The Corvette Hoverboard is Here and it’s Real',
        category: 'Hi-Tech',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-19.jpg',
    },
    {
        id: 20,
        title: 'Volkswagen e-Golf SEL Premium',
        category: 'Hi-Tech',
        author: 'Alex Reeve',
        date: 'December 28, 2015',
        description: defaultDescription,
        image: '/images/Posts/Cars-page/cars-page-20.jpg',
    },
]
export const postsReviewsArray: PropsPosts[] = [
    {
        id: 1,
        title: '2015 Chevrolet Camaro ZL1 Coupe',
        category: 'reviews',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Reviews-page/reviews-page-01.jpg',
    },
    {
        id: 2,
        title: 'Mercedes AMG C63 S Sedan',
        category: 'reviews',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Reviews-page/reviews-page-02.jpg',
    },
    {
        id: 3,
        title: 'Chevy Silverado Midnight Edition',
        category: 'reviews',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Reviews-page/reviews-page-03.jpg',
    },
    {
        id: 4,
        title: 'Volkswagen Golf SportWagen TDI',
        category: 'reviews',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Reviews-page/reviews-page-04.jpg',
    },
    {
        id: 5,
        title: '2016 Camaro Starts at $26.695',
        category: 'reviews',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Reviews-page/reviews-page-05.jpg',
    },
]
export const postsTestsArray: PropsPosts[] = [
    {
        id: 1,
        title: 'Land Rover Range Rover Sport’s New Diesel V6',
        category: 'tests',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Tests-page/tests-page-01.jpg',
    },
    {
        id: 2,
        title: 'The New Jaguar Crossover “F-Pace”',
        category: 'tests',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Tests-page/tests-page-02.jpg',
    },
    {
        id: 3,
        title: 'Ferrari Testing Right Hand Drive California',
        category: 'tests',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Tests-page/tests-page-03.jpg',
    },
    {
        id: 4,
        title: '2017 Ford Raptor Dominates Off-Road Trailchips',
        category: 'tests',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Tests-page/tests-page-04.jpg',
    },
    {
        id: 5,
        title: '2016 Mercedes CLS Coupe',
        category: 'tests',
        author: 'Alex Reeve',
        date: 'December',
        description: defaultDescription,
        image: '/images/Posts/Tests-page/tests-page-05.jpg',
    },
]
